-- MySQL Script generated by MySQL Workbench
-- 02/08/17 12:32:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda` ;

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`clientes` ;

CREATE TABLE IF NOT EXISTS `tienda`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(75) NOT NULL,
  `telefono` DECIMAL(9) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idclientes`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`cc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`cc` ;

CREATE TABLE IF NOT EXISTS `tienda`.`cc` (
  `entidad` DECIMAL(4) NOT NULL,
  `sucursal` DECIMAL(4) NOT NULL,
  `dc` DECIMAL(2) NOT NULL,
  `cuenta` DECIMAL(10) NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`entidad`, `sucursal`, `dc`, `cuenta`, `clientes_idclientes`),
  INDEX `fk_cc_clientes_idx` (`clientes_idclientes` ASC),
  CONSTRAINT `fk_cc_clientes`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `tienda`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`pedido` ;

CREATE TABLE IF NOT EXISTS `tienda`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NULL,
  `fecha_aceptacion` DATE NULL,
  `comentarios` VARCHAR(200) NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `clientes_idclientes`),
  INDEX `fk_pedido_clientes1_idx` (`clientes_idclientes` ASC),
  CONSTRAINT `fk_pedido_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `tienda`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`producto` ;

CREATE TABLE IF NOT EXISTS `tienda`.`producto` (
  `idproducto` INT NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`detalles` ;

CREATE TABLE IF NOT EXISTS `tienda`.`detalles` (
  `producto_idproducto` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `cantidad` DECIMAL(45) NOT NULL,
  `precio` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`producto_idproducto`, `pedido_idpedido`),
  INDEX `fk_producto_has_pedido_pedido1_idx` (`pedido_idpedido` ASC),
  INDEX `fk_producto_has_pedido_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_producto_has_pedido_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `tienda`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `tienda`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
