-- MySQL Script generated by MySQL Workbench
-- 02/07/17 09:50:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lugares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lugares` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lugares` (
  `idLugares` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idLugares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artistas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artistas` (
  `idArtistas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actividades` (
  `idActividades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idActividades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artistas_has_Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artistas_has_Actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artistas_has_Actividades` (
  `Artistas_idArtistas` INT NOT NULL,
  `Actividades_idActividades` INT NOT NULL,
  PRIMARY KEY (`Artistas_idArtistas`, `Actividades_idActividades`),
  INDEX `fk_Artistas_has_Actividades_Actividades1_idx` (`Actividades_idActividades` ASC),
  INDEX `fk_Artistas_has_Actividades_Artistas_idx` (`Artistas_idArtistas` ASC),
  CONSTRAINT `fk_Artistas_has_Actividades_Artistas`
    FOREIGN KEY (`Artistas_idArtistas`)
    REFERENCES `mydb`.`Artistas` (`idArtistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artistas_has_Actividades_Actividades1`
    FOREIGN KEY (`Actividades_idActividades`)
    REFERENCES `mydb`.`Actividades` (`idActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `idEventos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `Lugares_idLugares` INT NOT NULL,
  `Actividades_idActividades` INT NOT NULL,
  PRIMARY KEY (`idEventos`, `Lugares_idLugares`, `Actividades_idActividades`),
  INDEX `fk_Eventos_Lugares1_idx` (`Lugares_idLugares` ASC),
  INDEX `fk_Eventos_Actividades1_idx` (`Actividades_idActividades` ASC),
  CONSTRAINT `fk_Eventos_Lugares1`
    FOREIGN KEY (`Lugares_idLugares`)
    REFERENCES `mydb`.`Lugares` (`idLugares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Actividades1`
    FOREIGN KEY (`Actividades_idActividades`)
    REFERENCES `mydb`.`Actividades` (`idActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_has_Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria_has_Actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria_has_Actividades` (
  `categoria_idcategoria` INT NOT NULL,
  `Actividades_idActividades` INT NOT NULL,
  PRIMARY KEY (`categoria_idcategoria`, `Actividades_idActividades`),
  INDEX `fk_categoria_has_Actividades_Actividades1_idx` (`Actividades_idActividades` ASC),
  INDEX `fk_categoria_has_Actividades_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_categoria_has_Actividades_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_Actividades_Actividades1`
    FOREIGN KEY (`Actividades_idActividades`)
    REFERENCES `mydb`.`Actividades` (`idActividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
